name: CI

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check go version
        run: go version
      - name: Run linters
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          bash -c "$(go env GOPATH)/bin/staticcheck ./..."
      - name: Run Tests
        run: go test -coverprofile=coverage.txt -covermode=atomic ./...



